erDiagram
    address {
        uuid id PK"ID von Adresse"
        character_varying city "Postort, XPath: /juris-table/juris-gericht/postort"
        character_varying email "Email-Adresse, XPath: /juris-table/juris-gericht/email"
        character_varying fax_number "Telefax-Nummer, XPath: /juris-table/juris-gericht/telefax"
        character_varying phone_number "Telefonnummer, XPath: /juris-table/juris-gericht/telefon"
        character_varying post_office_box "Postfach, XPath: /juris-table/juris-gericht/postfach"
        character_varying post_office_box_location "Postfachort, XPath: /juris-table/juris-gericht/postfachort"
        character_varying post_office_box_postal_code "Postfachpostleitzahl, XPath: /juris-table/juris-gericht/postfachplz"
        character_varying postal_code "Postleitzahl, XPath: /juris-table/juris-gericht/plz"
        character_varying street "Strasse, XPath: /juris-table/juris-gericht/strasse"
        character_varying url "Website-Url, XPath: /juris-table/juris-gericht/internet"
    }

    case_facts {
        text value "Tatbestand, XPath: /juris-r/textdaten/tatbestand/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    court {
        uuid id PK"ID von Gericht"
        character_varying additional_information "Zusatz, XPath: /juris-table/juris-gericht/zusatz"
        character_varying belongs_to "Gehört zu, XPath: /juris-table/juris-gericht/gehoertzu"
        character_varying belongs_to_branch "Ist Zweigstelle zu, XPath: /juris-table/juris-gericht/istzweigstellezu"
        boolean can_deliver_lrs "Liefert lrs, XPath: /juris-table/juris-gericht/liefertlrs"
        character_varying current_branch "Bestehende Zweigstelle, XPath: /juris-table/juris-gericht/bestzweigstelle"
        character_varying deprecated_branch "Aufgehobene Zweigstelle, XPath: /juris-table/juris-gericht/aufgehzweigstelle"
        date deprecated_since "Aufgehoben seit, XPath: /juris-table/juris-gericht/aufhebdatum"
        character_varying early_name "Frühname, XPath: /juris-table/juris-gericht/fruehname"
        date exists_since "Bestehdatum, XPath: /juris-table/juris-gericht/bestehdatum"
        character_varying field "Bereich, XPath: /juris-table/juris-gericht/bereich"
        boolean is_foreign_court "Ausland, XPath: /juris-table/juris-gericht/ausland"
        boolean is_superior_court "Übergeordnetes Gericht, XPath: /juris-table/juris-gericht/supra"
        integer juris_id "Juris-Gericht ID, XPath: /juris-table/juris-gericht/@id"
        character_varying late_name "Spätname, XPath: /juris-table/juris-gericht/spaetname"
        character_varying location "Gerichtsort, XPath: /juris-table/juris-gericht/gerort"
        character_varying official_name "Offizeller Name, XPath: /juris-table/juris-gericht/offizname"
        character_varying remark "Bemerkung, XPath: /juris-table/juris-gericht/bemerkung"
        character_varying traditional_name "Traditioneller Name, XPath: /juris-table/juris-gericht/tradname"
        character_varying type "Gerichtstyp, XPath: /juris-table/juris-gericht/gertyp"
        uuid address_id FK"ID von Adresse"
    }

    court_judicial_body {
        uuid court_id PK"ID von Gericht"
        uuid judicial_body_id PK"ID von Spruchkörper"
    }

    court_region {
        uuid court_id PK"ID von Gericht"
        uuid region_id PK"ID von Region"
    }

    court_synonym {
        uuid court_id PK"ID von Gericht"
        uuid synonym_id PK"ID von Synonym"
    }

    decision_grounds {
        text value "Entscheidungsgründe, XPath: /juris-r/textdaten/entscheidungsgruende/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    deviating_document_number {
        uuid id PK"ID von Abweichende Dokumentnummer"
        character_varying value "Abweichende Dokumentnummer, XPath: /juris-r/paratrubriken/zuordnung/aspekt[text()='abweichende Nr']/following-sibling::begriff"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    document_category {
        uuid id PK"ID von Dokumentart"
        character_varying label "Kürzel"
    }

    document_type {
        uuid id PK"ID von Dokumenttyp"
        character_varying abbreviation "Juris-Abkürzung, XPath: /juris-table/juris-doktyp/jurisabk"
        character_varying label "Bezeichnung, XPath: /juris-table/juris-doktyp/bezeichnung"
        boolean multiple "Mehrfach, XPath: /juris-table/juris-doktyp/mehrfach"
        character_varying super_label_1 "Überbezeichnung 1, XPath: /juris-table/juris-doktyp/ueberbezeichnung1"
        character_varying super_label_2 "Überbezeichnung 2, XPath: /juris-table/juris-doktyp/ueberbezeichnung2"
        uuid document_category_id FK"ID von Dokumentart"
    }

    documentation_office {
        uuid id PK"ID von Dokumentationsstelle"
        character_varying abbreviation "Abkürzung"
    }

    documentation_unit {
        uuid id PK"ID von Dokumentationseinheit"
        date decision_date "Entscheidungsdatum, XPath: /juris-r/metadaten/entsch-datum"
        character_varying document_number "Dokumentnummer, XPath: /juris-r/@doknr"
        uuid document_type_id FK"ID von Dokumenttyp"
        uuid documentation_office_id FK"ID von Dokumentationsstelle"
        character_varying ecli "ECLI, XPath: /juris-r/metadaten/ecli"
        character_varying judicial_body "Spruchkörper, XPath: /juris-r/metadaten/spruchkoerper"
        character_varying procedure "Vorgang, XPath: /juris-r/paratrubriken/zuordnung/aspekt[text()='Vorgang']/following-sibling::begriff"
    }

    documentation_unit_keyword {
        uuid documentation_unit_id PK"ID von Dokumentationseinheit"
        uuid keyword_id PK"ID von Schlagwort"
    }

    documentation_unit_region {
        uuid documentation_unit_id PK"ID von Dokumentationseinheit"
        uuid region_id PK"ID von Region"
    }

    file_number {
        uuid id PK"ID von Aktenzeichen"
        character_varying value "Aktenzeichen, XPath: /juris-r/metadaten/aktenzeichen"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    flyway_schema_history {
        integer installed_rank PK
        character_varying version 
        character_varying description 
        character_varying type 
        character_varying script 
        integer checksum 
        character_varying installed_by 
        timestamp_without_time_zone installed_on 
        integer execution_time 
        boolean success 
    }

    grounds {
        text value "Gründe, XPath: /juris-r/textdaten/gruende/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    guiding_principle {
        text value "Leitsatz, XPath: /juris-r/textdaten/leitsatz/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    headline {
        text value "Titelzeile, XPath: /juris-r/textdaten/titelzeile/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    headnote {
        text value "Orientierungssatz, XPath: /juris-r/textdaten/osatz/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    input_type {
        text value "Eingangsart, XPath: /juris-R/paratrubriken/zuordnung/aspekt[text()='Eingangsart']/following-sibling::begriff"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    judicial_body {
        uuid id PK"ID von Spruchkörper"
        character_varying name "Name, XPath: /juris-table/juris-gericht/spruchkoerper/name"
        uuid numeric_figure_id FK"ID von Zahlangabe"
    }

    keyword {
        uuid id PK"ID von Schlagwort"
        character_varying value "Schlagwort, XPath: /juris-r/metadaten/schlagwort"
    }

    norm_abbreviation {
        uuid id PK"ID von Norm (Wertetabelle)"
        character_varying abbreviation "Juris-Abkürzung, XPath: /juris-norm/metadaten/jurabk"
        date decision_date "Entscheidungsdatum, XPath: /juris-norm/metadaten/entsch-datum"
        bigint document_id "Dokument ID, XPath: /juris-norm/metadaten/dokid"
        character_varying document_number "Dokumentnummer, XPath: /juris-norm/metadaten/doknr"
        character_varying official_letter_abbreviation "Amtliche Buchstabenabkürzung, XPath: /juris-norm/metadaten/amtabk"
        text official_long_title "Amtliche Langüberschrift, XPath: /juris/metadaten/langue"
        text official_short_title "Amtliche Kurzüberschrift, XPath: /juris/metadaten/kurzue"
        character_varying source "Quelle, XPath: /juris/metadaten/quelle"
    }

    norm_abbreviation_document_type {
        uuid norm_abbreviation_id PK"ID von Normabkürzung"
        uuid document_type_id PK"ID von Dokumenttyp"
    }

    norm_abbreviation_region {
        uuid norm_abbreviation_id PK"ID von Normabkürzung"
        uuid region_id PK"ID von Region"
    }

    norm_element {
        uuid id PK"ID von Norm Element"
        character_varying label "Bezeichnung, XPath: /juris-table/juris-normelem/element"
        boolean has_number_designation "Mit Zählbezeichnung, Negation von XPath: /juris-table/juris-normelem/ohnezaehlbezeichnung"
        character_varying norm_code "Normabkürzung, XPath: /juris-table/juris-normelem/normabk"
        uuid document_category_id FK"ID von Dokumentart"
    }

    numeric_figure {
        uuid id PK"ID von Zahlangabe"
        character_varying from_value "Von Nummer, XPath: /juris-table/juris-gericht/spruchkoerper/zahlangabe/vonnr"
        character_varying to_value "Bis Nummer, XPath: /juris-table/juris-gericht/spruchkoerper/zahlangabe/bisnr"
        character_varying type "Typ, XPath: /juris-table/juris-gericht/spruchkoerper/zahlangabe/@typ"
    }

    region {
        uuid id PK"ID von Region"
        character_varying code "Kürzel"
        character_varying label "Bezeichnung"
    }

    related_documentation {
        uuid id PK"ID von Zugehörige Dokumentation"
        character_varying court_location "Gerichtssitz, XPath: /juris-r/metadaten/vorinstanz/gericht/gerort"
        character_varying court_type "Gerichtstyp, XPath: /juris-r/metadaten/vorinstanz/gericht/gertyp"
        date date "Datum, XPath: /juris-r/metadaten/vorinstanz/datum"
        character_varying document_number "Dokumentnummer, XPath: /juris-r/metadaten/vorinstanz/hlj/@sw"
        character_varying document_type "Dokumenttyp, XPath: /juris-r/metadaten/vorinstanz/doktyp"
        character_varying file_number "Aktenzeichen, XPath: /juris-r/metadaten/vorinstanz/az"
        character_varying dtype "Art der Zugehörigen Dokumentation (mögliche Werte: 'previous_decision')"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    synonym {
        uuid id PK"ID von Synonym"
        character_varying label "Synonymbezeichnung,  XPath: /juris-table/juris-gericht/synonym/synbez"
        character_varying type "Synonymtyp, XPath: /juris-table/juris-gericht/synonym/syntyp"
    }

    tenor {
        text value "Tenor, XPath: /juris-r/textdaten/tenor/body/div"
        uuid documentation_unit_id FK"ID von Dokumentationseinheit"
    }

    court }o--|| address : "address_id"
    case_facts }o--|| documentation_unit : "documentation_unit_id"
    court_synonym }o--|| court : "court_id"
    court_region }o--|| court : "court_id"
    court_judicial_body }o--|| court : "court_id"
    court_judicial_body }o--|| judicial_body : "judicial_body_id"
    court_region }o--|| region : "region_id"
    court_synonym }o--|| synonym : "synonym_id"
    decision_grounds }o--|| documentation_unit : "documentation_unit_id"
    deviating_document_number }o--|| documentation_unit : "documentation_unit_id"
    norm_element }o--|| document_category : "document_category_id"
    document_type }o--|| document_category : "document_category_id"
    norm_abbreviation_document_type }o--|| document_type : "document_type_id"
    documentation_unit }o--|| document_type : "document_type_id"
    documentation_unit }o--|| documentation_office : "documentation_office_id"
    tenor }o--|| documentation_unit : "documentation_unit_id"
    input_type }o--|| documentation_unit : "documentation_unit_id"
    documentation_unit_region }o--|| documentation_unit : "documentation_unit_id"
    documentation_unit_keyword }o--|| documentation_unit : "documentation_unit_id"
    file_number }o--|| documentation_unit : "documentation_unit_id"
    guiding_principle }o--|| documentation_unit : "documentation_unit_id"
    headnote }o--|| documentation_unit : "documentation_unit_id"
    headline }o--|| documentation_unit : "documentation_unit_id"
    grounds }o--|| documentation_unit : "documentation_unit_id"
    related_documentation }o--|| documentation_unit : "documentation_unit_id"
    documentation_unit_keyword }o--|| keyword : "keyword_id"
    documentation_unit_region }o--|| region : "region_id"
    judicial_body }o--|| numeric_figure : "numeric_figure_id"
    norm_abbreviation_document_type }o--|| norm_abbreviation : "norm_abbreviation_id"
    norm_abbreviation_region }o--|| norm_abbreviation : "norm_abbreviation_id"
    norm_abbreviation_region }o--|| region : "region_id"
