title: Reports for RIS
description: Reports and GitHub Page for RIS
theme: just-the-docs

url: https://digitalservicebund.github.io/ris-reports

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
